push if scan succeeds

diff --git a/.github/workflows/_container_build.yml b/.github/workflows/_container_build.yml
--- a/.github/workflows/_container_build.yml
+++ b/.github/workflows/_container_build.yml
@@ -74,6 +74,7 @@ jobs:
     permissions:
       contents: read
       id-token: write
+      security-events: write
 
     timeout-minutes: 30
 
@@ -116,6 +117,7 @@ jobs:
             type=semver,pattern={{version}}
             type=semver,pattern={{major}}.{{minor}}
             type=raw,value=main,enable=${{ inputs.push-main-tag && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
+            type=raw,value=DO-NOT-USE
           labels: |
             org.opencontainers.image.title=${{ inputs.service-name }}
             org.opencontainers.image.description=${{ inputs.service-name }} JavaScript service
@@ -137,13 +139,6 @@ jobs:
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069  # v4.4.1
-
-#      - name: Validate Docker build configuration
-#        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc  # v7.4.0
-#        with:
-#          context: ${{ inputs.service-directory }}
-#          file: ${{ inputs.dockerfile }}
-#          call: check
 
       - name: Build container image
         id: build
@@ -179,37 +174,39 @@ jobs:
 
       # Scan the image before it is pushed
       - name: Scan image with Trivy
+#        if: ${{ matrix.target == 'production' }}
         id: trivy-scan
         uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
         with:
           image-ref: ${{ fromJson(steps.metadata.outputs.json).tags[0] }}
-#          input: ./${{ inputs.service-name }}_image.tar
           format: table
           severity: CRITICAL,HIGH
           ignore-unfixed: true
           exit-code: 1
 
-      - name: Show scan outcome
+      - name: Trivy scan outcome
         run: |
           echo "Outcome of Trivy Scan is ${{ steps.trivy-scan.outcome }}"     
 
       # Upload SARIF results to GitHub Security
       - name: Generate SARIF report
+#        if: ${{ matrix.target == 'production' }}
         if: always()
         uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
         with:
           image-ref: ${{ fromJson(steps.metadata.outputs.json).tags[0] }}
-#          input: ./${{ inputs.service-name }}_image.tar
           format: sarif
           output: trivy-results.sarif
 
       - name: Upload SARIF report
+#        if: ${{ matrix.target == 'production' }}
         if: always()
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: trivy-results.sarif
 
       - name: Fail build if scans failed
+#        if: ${{ matrix.target == 'production' && steps.trivy-scan.outcome == 'failure' }}
         if: ${{ steps.trivy-scan.outcome == 'failure' }}
         run: |
           echo "One or more scans failed. Failing the build."
@@ -223,30 +220,30 @@ jobs:
           role-session-name: github-actions-${{ github.run_id }}
           mask-aws-account-id: true
 
-#      - name: Sign in to Amazon ECR
-#        id: ecr-login
-#        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd  # v2.1.7
-#        with:
-#          mask-password: true
-#
-#      - name: Set image repository
-#        id: image
-#        shell: bash
-#        env:
-#          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
-#          ECR_REPOSITORY: ${{ inputs.ecr-repository }}
-#        run: |
-#          set -euo pipefail
-#
-#          image_uri="${ECR_REGISTRY}/${ECR_REPOSITORY}"
-#
-#          echo "image-uri=${image_uri}" >> "${GITHUB_OUTPUT}"
-#          echo "IMAGE_URI=${image_uri}" >> "${GITHUB_ENV}"
+      - name: Sign in to Amazon ECR
+        id: ecr-login
+        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd  # v2.1.7
+        with:
+          mask-password: true
 
-      # TODO: Push only if scan passed
-#      - name: Push container image
-#        run: |
-#          docker push ${{ fromJson(steps.metadata.outputs.json).tags[0] }}
+      - name: Set image repository
+        id: image
+        shell: bash
+        env:
+          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
+          ECR_REPOSITORY: ${{ inputs.ecr-repository }}
+        run: |
+          set -euo pipefail
+
+          image_uri="${ECR_REGISTRY}/${ECR_REPOSITORY}"
+
+          echo "image-uri=${image_uri}" >> "${GITHUB_OUTPUT}"
+          echo "IMAGE_URI=${image_uri}" >> "${GITHUB_ENV}"
+
+      # We didn't exit so scan passed. Push image.
+      - name: Push container image
+        run: |
+          docker push ${{ fromJson(steps.metadata.outputs.json).tags[0] }}
 
       - name: Set immutable image reference
         id: result
