add fail step if trivy scan fails

diff --git a/.github/workflows/_container_build.yml b/.github/workflows/_container_build.yml
--- a/.github/workflows/_container_build.yml
+++ b/.github/workflows/_container_build.yml
@@ -153,7 +153,7 @@ jobs:
 #          file: ${{ inputs.dockerfile }}
 #          call: check
 
-      - name: Build and push container image
+      - name: Build container image
         id: build
         uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc  # v7.4.0
         with:
@@ -185,10 +185,10 @@ jobs:
         run: |
           docker images
           docker save ${{inputs.service-name}} -o ${{ inputs.service-name }}_image.tar
-          ls -lh ${{ inputs.service-name }}_image.tar
 
       # Scan the image before it is pushed
       - name: Scan image with Trivy
+        id: trivy-scan
         uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
         with:
           image-ref: ${{ fromJson(steps.metadata.outputs.json).tags[0] }}
@@ -213,6 +213,12 @@ jobs:
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: trivy-results.sarif
+
+      - name: Fail build if scans failed
+        if: ${{ steps.trivy-scan.outcome == 'failure' }}
+        run: |
+          echo "One or more scans failed. Failing the build."
+          exit 1
 
       #      - name: Sign in to Amazon ECR
       #        id: ecr-login
